# Generated by Django 4.0.4 on 2022-05-10 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BUG', 'BUG'), ('IDEA', 'IDEA'), ('OTHER', 'OTHER')], max_length=5)),
                ('comment', models.TextField()),
                ('screenshot', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'feedbacks',
            },
        ),
    ]
